# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: objective-c
#CODECOV_TOKEN="fd01720b-f834-4807-913f-4c8e20fd580b"
#xcode_workspace: Example/XFoundation.xcworkspace
#xcode_scheme: XFoundation_Tests
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X

cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods -v 1.5.3 --no-rdoc --no-ri --no-document --quiet
- pod install --project-directory=Example
script:
- cd Example/
- ls
- xcodebuild test -enableCodeCoverage YES -workspace XFoundation.xcworkspace -scheme XFoundation_Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.0,name=iPhone X' ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
#- xctool -workspace XFoundation.xcworkspace -scheme XFoundation_Tests run-tests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.1,name=iPhone X' ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
#- cd ..
#- pod lib lint --allow-warnings

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'XFoundation'

